### PR TITLE
feature: Add imagePullSecrets to enable private repository

### PR DESCRIPTION
**Pull request by Bengreen**
# Pull Request Template

## Description
When deployment in many environments the images are provided via a private repository.
Private repository's require imagePullSecrets.
This PR adds imagePullSecrets to the values file of the chart AND uses it to provide the imagePullSecrets to the deployment.
If no secrets are provided (default) the imagePullSecrets is not applied to the deployment.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Pull Request contain one commit. I squash my commits

### CODE REVIEW

**Review by Arania — APPROVED** [review]
Looks good to me. Would be a good addition as this is a common use case.

**Comment by SergK** [comment]
Hi @Bengreen, can you please run:

1.  'make helm-docs',
2. rebase on the latest changes from master
3. fix the commit message by setting 'feat' instead of 'feature'

Thank you

**Comment by Bengreen** [comment]
@SergK I have rebased, run `make helm-docs` and then updated the PR branch.

**Review by SergK — APPROVED** [review]
@Bengreen Thank you

**Pull request merged**
